version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: ./docker/python.Dockerfile
    volumes:
      - .:/usr/src/app
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      # Other environment variables
    ports:
      - "6000:6000" # Map port 5000 of the container to port 5000 on the host

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432" # Map port 5432 of the container to port 5432 on the host

volumes:
  postgres_data:
